services:
  traefik:
    image: "traefik:3.6.9"
    container_name: "traefik"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - ACME_EMAIL=${ACME_EMAIL}
      - DASHBOARD_DOMAIN=${DASHBOARD_DOMAIN}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/traefik/letsencrypt:/letsencrypt
      - /data/traefik/config:/etc/traefik
      - /etc/localtime:/etc/localtime

    command:
      # EntryPoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"

      # Providers
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # - "--providers.docker.network=proxy"

      # API & Dashboard
      - "--api.dashboard=true"
      - "--api.insecure=false"

      # Observability
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--metrics.prometheus=true"

      # Let's Encrypt with Cloudflare DNS Challenge
      - "--certificatesresolvers.le.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.le.acme.dnschallenge.delaybeforecheck=5"
      - "--certificatesresolvers.le.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"

      # Make 'le' the default resolver for all TLS-enabled routers
      - "--entrypoints.websecure.http.tls.certresolver=le"

    labels:
      # Enable self‑routing
      - "traefik.enable=true"

      # Dashboard router — protected by Let's Encrypt certificate
      - "traefik.http.routers.dashboard.rule=Host(`${DASHBOARD_DOMAIN}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=le"

      # Basic‑auth middleware
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=IwQ2CnpxGmk1OKSgjmVt7Uu6R91d4ZMI:$$apr1$$y0OYGbBt$$gVeBp61pLFMQnKxQbjqa6."
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth@docker"

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
